http://localhost:1337/api/user


###
POST http://localhost:1337/api/auth/local/
content-type: application/json
{
    "identifier": "test@test.com",
    "password": "admin1"
}

###

POST /api/auth/local/ HTTP/1.1
Host: localhost:1337
Content-Type: application/json
Content-Length: 66

{
    "identifier": "test@test.com",
    "password": "admin1"
}
   
    

    

